"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
required: ["bridge", "auth"]
properties:
    bridge:
        type: "object"
        required: ["domain", "homeserverUrl"]
        properties:
          domain:
            type: "string"
          homeserverUrl:
            type: "string"
          presenceInterval:
            type: "number"
          disablePresence:
            type: "boolean"
          disableTypingNotifications:
            type: "boolean"
          disableDiscordMentions:
            type: "boolean"
          disableDeletionForwarding:
            type: "boolean"
          enableSelfServiceBridging:
            type: "boolean"
    auth:
        type: "object"
        required: ["botToken"]
        properties:
          clientID:
            type: "string"
          secret:
            type: "string"
          botToken:
            type: "string"
    logging:
        type: "object"
        required: ["level"]
        properties:
          level:
            type: "string"
    database:
        type: "object"
        required: ["filename"]
        properties:
          filename:
            type: "string"
    room:
        type: "object"
        required: ["defaultVisibility"]
        properties:
          defaultVisibility:
            type: "string"
