"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
required: ["bridge", "auth"]
properties:
    bridge:
        type: "object"
        required: ["domain", "homeserverUrl"]
        properties:
          domain:
            type: "string"
          homeserverUrl:
            type: "string"
          port:
            type: "number"
          presenceInterval:
            type: "number"
          disablePresence:
            type: "boolean"
          disableTypingNotifications:
            type: "boolean"
          disableDeletionForwarding:
            type: "boolean"
          disablePortalBridging:
            type: "boolean"
          enableSelfServiceBridging:
            type: "boolean"
          disableReadReceipts:
            type: "boolean"
          disableJoinLeaveNotifications:
            type: "boolean"
          disableInviteNotifications:
            type: "boolean"
          disableRoomTopicNotifications:
            type: "boolean"
          disableDiscordReplyPings:
            type: "boolean"
          userActivity:
            type: "object"
            required: ["minUserActiveDays", "inactiveAfterDays"]
            properties:
              minUserActiveDays:
                type: "number"
              inactiveAfterDays:
                type: "number"
          userLimit:
            type: "number"
    auth:
        type: "object"
        required: ["botToken", "clientID"]
        properties:
          clientID:
            type: "string"
          botToken:
            type: "string"
          usePrivilegedIntents:
            type: "boolean"
    logging:
        type: "object"
        properties:
          console:
            type: "string"
            enum: ["error", "warn", "info", "verbose", "silly", "silent"]
          lineDateFormat:
            type: "string"
          files:
            type: "array"
            items:
              type: "object"
              required: ["file"]
              properties:
                file:
                  type: "string"
                level:
                  type: "string"
                  enum: ["error", "warn", "info", "verbose", "silly"]
                maxFiles:
                  type: "string"
                maxSize:
                  type: ["number", "string"]
                datePattern:
                  type: "string"
                enabled:
                  type: "array"
                  items:
                    type: "string"
                disabled:
                  type: "array"
                  items:
                    type: "string"
    database:
        type: "object"
        properties:
          connString:
            type: "string"
          filename:
            type: "string"
          userStorePath:
            type: "string"
          roomStorePath:
            type: "string"
    room:
        type: "object"
        properties:
          defaultVisibility:
            type: "string"
            enum: ["public", "private"]
    limits:
        type: "object"
        properties:
            roomGhostJoinDelay:
                type: "number"
            discordSendDelay:
                type: "number"
            roomCount:
                type: "number"
    channel:
        type: "object"
        properties:
            namePattern:
                type: "string"
            deleteOptions:
                type: "object"
                properties:
                   namePrefix:
                       type: "string"
                   topicPrefix:
                       type: "string"
                   disableMessaging:
                     type: "boolean"
                   unsetRoomAlias:
                     type: "boolean"
                   unlistFromDirectory:
                     type: "boolean"
                   setInviteOnly:
                     type: "boolean"
                   ghostsLeave:
                     type: "boolean"
    ghosts:
        type: "object"
        properties:
            nickPattern:
                type: "string"
            usernamePattern:
                type: "string"
    metrics:
        type: "object"
        properties:
            enable:
                type: "boolean"
            port:
                type: "number"
            host:
                type: "string"
